services:

  postgres:
    image: postgres:16
    container_name: passport_postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: passport
      POSTGRES_PASSWORD: passport_password
      POSTGRES_DB: passport_db

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: